---
title: "Fayaz Seifuddin's CV"
author: Fayaz Seifuddin
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{css, echo=FALSE}
.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "/Users/seifuddf/Documents/00-create_cv/datadrivencv/data/",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
# datadrivencv::build_network_logo(CV$entries_data)
```


<!--```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _nickstrayer.me/datadrivencv/_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/nstrayer/cv/raw/master/strayer_cv.pdf)")
}
```
-->

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV |> print_contact_info()
```

Publications {#publications}
--------------------------------------------------------------------------------

```{r}
CV |> print_publications_info()
```

Computational Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV |> print_skill_bars()
```

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available [on github.com/seifudd/cv](https://github.com/seifudd/cv).

Last updated on `r Sys.Date()`.

Main
================================================================================

Fayaz Seifuddin {#title}
--------------------------------------------------------------------------------

<!--```{r}
# Note the assignment back to CV. This is so the link stripping works properly in PDF mode
CV <- print_text_block(CV, "intro") 
```
-->

Background {data-icon=binoculars data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'introduction')
```

Employment {data-icon=suitcase data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'employment')
```

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'education')
```

Industry & Academic Experience {data-icon=laptop data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'research_experience')
```

Teaching Experience {data-icon=chalkboard-teacher data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'teaching_experience')
```

Honors and Awards {data-icon=trophy data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'honors_and_awards')
```

